2648 konvertere dropdown til ts
NDLANO/editorial-frontend pull request #1094
Opened 2021-07-23 08:22 UTC by sigrunnu

Fixes https://github.com/NDLANO/Issues/issues/2648

2021-07-28 11:30 UTC, Jonas-C requested changes
Ser bra ut! Hadde vært fint å få fjernet litt props som ikke brukes til noe, samt å fjerne `undefined` som mulig returtype på `AsyncDropdown` sin `onChange`.

2021-07-28 11:30 UTC, Jonas-C commented on src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
> +  const [currentDebounce, setCurrentDebounce] = useState<{ cancel: Function } | undefined>();
Trenger ikke `| undefined`.

2021-07-28 11:30 UTC, Jonas-C commented on src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
> +    async (query = '', page: number) => {
Query vil her være av typen `any`. Kan den være mer spesifikk?

2021-07-28 11:30 UTC, Jonas-C commented on src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
Hadde vært fint å flytte denne lenger opp, rett under der state er definert. Da er det mer åpenbart om noe utføres når komponenten først initialiseres.

2021-07-28 11:30 UTC, Jonas-C commented on src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
> +    }
Hvis `selectedItem` ikke kan være `null | undefined` vil ikke if-else-blokkene gjøre noe. Den vil alltid gå til else.

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/ArticlePage/components/ConceptsField.tsx
> +      const newConcept = await fetchConcept(concept!.id, locale);
Denne vil vel i teorien aldri være null eller undefined, men "kan" være det fordi `AsyncDropdown` sin `onChange` kan returnere det. Hvis `onChange` endres bør dette endret til å være non-null.

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/ArticlePage/components/ConceptsField.tsx
>        if (newConcept) {
Da vil man heller ikke trenge if-blokken på `newConcept`, da den enten returnerer et konsept eller kaster en feil.

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/ArticlePage/components/ContentField.tsx
> +        // @ts-ignore
Hvorfor er det en ts-ignore her?

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/ArticlePage/components/ContentField.tsx
>        // @ts-ignore TODO Temporary ugly hack for mismatching Article types, should be fixed when ConceptForm.jsx -> tsx
Tror det skal være mulig å fikse denne kommentaren nå også.

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/ConceptPage/components/ConceptArticles.tsx
> +  const onAddArticleToList = async (article?: ArticleType) => {
Samme som før, dette bør endres hvis `AsyncDropdown onChange` endres.

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/FormikForm/GrepCodesFieldContent.tsx
> +  const createNewGrepCodes = async (input?: string) => {
Endre hvis `AsyncDropdown onChange` endres.

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/Podcast/components/PodcastSeriesInformation.tsx
> +  const onAddSeries = async (series?: PodcastSeriesApiType) => {
Endre hvis `AsyncDropdown onChange` endres.

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/PodcastSeries/components/PodcastEpisodes.tsx
> +  const onAddEpisodeToList = async (audio?: AudioApiType) => {
Endre hvis `AsyncDropdown onChange` endres.

2021-07-28 11:30 UTC, Jonas-C commented on src/containers/StructurePage/resourceComponents/AddResourceModal.tsx
> +  const onSelect = (selected?: SelectedType) => {
Endre hvis `AsyncDropdown onChange` endres.

2021-08-09 13:09 UTC, Jonas-C reviewed
Ser bra ut, småpirk bare.

2021-08-09 13:09 UTC, Jonas-C commented on src/components/Dropdown/asyncDropdown/AsyncSearchTags.tsx
> +  const addTag = (tag?: TagWithTitle) => {
Trenger ikke være optional.

2021-08-11 07:17 UTC, haalmarc commented on src/containers/PodcastSeries/components/PodcastEpisodes.tsx
> +      const newAudio = await fetchAudio(audio!.id, language);
Her sies at audio eksisterer. Funksjonen benyttes ved valg av elementer i dropdown, og fungerer ikke å gjøre tomme valg. Så gir mening at audio må eksistere. Men så ikke ut til at man trengte å legge inn `!` her, så tror jeg kan fjerne den..

2021-08-11 07:19 UTC, haalmarc commented on src/containers/ConceptPage/components/ConceptArticles.tsx
> +      const newArticle = await fetchDraft(article!.id);
SAmme som over

2021-08-12 08:29 UTC, Jonas-C approved these changes
LGTM, men kanskje fint med et ekstra par med øyne!

2021-08-13 08:18 UTC, brdalsnes reviewed
Ser ellers bra ut

2021-08-13 08:18 UTC, brdalsnes commented on src/components/Dropdown/asyncDropdown/AsyncDropdown.tsx
> +) => any;
Denne konverteringen blir ikke helt riktig (hovre over AsyncDropdown i vscode for å se den infererte typen). Det ser ut som type konverteringen bare er nødvendig pga injectT, men t brukes ikke i komponenten så det er bare å fjerne injectT og as. Ser da at det dukker opp en type feil i ContentField og kanskje andre steder, så det bør fikses

2021-08-13 08:18 UTC, brdalsnes commented on src/components/Dropdown/MultiSelectDropdown.tsx
> +export default MultiSelectDropdown as <T>(props: Props<T>) => any;
Er denne nødvendig?

2021-09-13 14:25 UTC, haattis reviewed
Har noen få kommentarer. Ellers ser det bra ut!

2021-09-13 14:25 UTC, haattis commented on src/containers/ArticlePage/components/ContentField.tsx
> +  };
Mer spesifikk om mulig. Denne brukes bare et sted og typen som sendes inn i funksjonen her er `ConvertedRelatedContent`

2021-09-14 13:27 UTC, Jonas-C commented on src/components/Dropdown/MultiSelectDropdown.tsx
> +    if (shouldCreate(value, inputValue)) {
Da blir det vanskeligere å gjøre den generisk. Denne funksjonaliteten brukes bare ett sted, og er litt spesiell. Tar gjerne i mot forslag til bedre løsninger.

2021-09-21 08:15 UTC, Jonas-C commented
Fixes https://github.com/NDLANO/Issues/issues/2754
Fixes https://github.com/NDLANO/Issues/issues/2648

2021-09-21 13:50 UTC, haattis approved these changes
Har testet flere av sidene der dropdown brukes og det ser ut til å fungere fint.

2021-09-24 06:35 UTC, merged