Preview Pages to TS.
NDLANO/editorial-frontend pull request #1177
Opened 2021-09-16 12:51 UTC by Jonas-C

Det er en del typer som er litt kinkige her inne, men jeg fikk fjernet et par overflødige og fikk ryddet opp litt.

2021-09-17 10:32 UTC, haattis requested changes

2021-09-17 10:32 UTC, haattis commented on src/components/PreviewConcept/PreviewConceptLightbox.tsx
>      );
Ble umiddelbart litt forvirret pga shadowing. Bytte variabel-navn fra secondConcept så den ikke deler navn med state?

2021-09-17 10:32 UTC, haattis commented on src/components/PreviewDraft/PreviewLanguage.tsx
> +            {secondEntity.supportedLanguages.map(language => (
Er det meningen at denne skal byttes fra firstEntity?

2021-09-17 10:32 UTC, haattis commented on src/components/SlateEditor/EditorFooter.tsx
> +  return (entity() as ConceptType).parsedVisualElement !== undefined;
En forklaring trenger ikke å ha et visuelt element. Lurer derfor på om ConceptType er typet feil?

2021-09-17 10:32 UTC, haattis commented on src/modules/article/articleApiInterfaces.ts
> +// editorLabels: array of something
Fjerne kommentarer?

2021-09-27 12:25 UTC, Jonas-C commented on src/components/SlateEditor/EditorFooter.tsx
> +  return (entity() as ConceptType).parsedVisualElement !== undefined;
Det har du helt rett i. Det er dog såpass mange forskjellige konsept-typer at å endre på noe sånt bør gjøres i en egen PR.

2021-09-27 13:41 UTC, haattis commented on src/components/SlateEditor/EditorFooter.tsx
> +  return (entity() as ConceptType).parsedVisualElement !== undefined;
Lurt

2021-09-28 07:16 UTC, haattis approved these changes
LGTM 🙌 Har testet denne i PR-instans nå og har ikke støtt på noen feil.

2021-09-28 07:27 UTC, gunnarvelle commented
Pr må oppdateres med endringer fra master der to forskjellige språkversjoner vises ved sammenlig språkversjoner.

2021-10-01 07:52 UTC, merged